import math

class Turtle:
    def __init__(self):
        self._x = 0
        self._y = 0
        self._angle = 0
        self._pen = True
        self._color = "black"
        self._width = 2
        self._js_actions = []

    # ----------------- JS Storage -----------------
    def getJsActions(self):
        """Return the list of JS actions (internal use)."""
        return self._js_actions

    # ----------------- Movement -----------------
    def forward(self, distance):
        rad = math.radians(self._angle)
        new_x = self._x + distance * math.cos(rad)
        new_y = self._y + distance * math.sin(rad)
        if self._pen:
            self._js_actions.append(
                f"ctx.beginPath(); ctx.moveTo({self._x}, {self._y}); ctx.lineTo({new_x}, {new_y}); "
                f"ctx.strokeStyle='{self._color}'; ctx.lineWidth={self._width}; ctx.stroke();"
            )
        self._x, self._y = new_x, new_y

    def backward(self, distance):
        self.forward(-distance)

    def right(self, angle):
        self._angle -= angle

    def left(self, angle):
        self._angle += angle

    def goto(self, x, y):
        if self._pen:
            self._js_actions.append(
                f"ctx.beginPath(); ctx.moveTo({self._x}, {self._y}); ctx.lineTo({x}, {y}); "
                f"ctx.strokeStyle='{self._color}'; ctx.lineWidth={self._width}; ctx.stroke();"
            )
        self._x, self._y = x, y

    def setHeading(self, angle):
        self._angle = angle
        return self._angle

    def getHeading(self):
        return self._angle

    # ----------------- Pen -----------------
    def setPen(self, value: bool):
        self._pen = bool(value)
        return self._pen

    def getPen(self):
        return self._pen

    def setColor(self, color):
        self._color = color
        return self._color

    def getColor(self):
        return self._color

    def setLineWidth(self, w):
        self._width = w
        return self._width

    def getLineWidth(self):
        return self._width

    # ----------------- Utility -----------------
    def getPosition(self):
        return (self._x, self._y)

    # ----------------- Generate JS -----------------
    def getJs(self):
        js_code = [
            "// Generated by Python Turtle",
            "const canvas = document.getElementById('t-canvas');",
            "const ctx = canvas.getContext('2d');",
        ]
        js_code.extend(self._js_actions)
        return "\n".join(js_code)
